app/monitor/forms.py
#! /usr/bin/env python
# _*_coding:utf-8 -*_

from flask_wtf import FlaskForm
from wtforms import SubmitField


class ScanControlForm(FlaskForm):
    submit_start_scan = SubmitField('开始扫描')
    submit_stop_scan = SubmitField('停止扫描')

app/task/forms.py
#! /usr/bin/env python
# _*_coding:utf-8 -*_

from flask_wtf import FlaskForm
from wtforms import StringField,  SelectField,SubmitField
from wtforms.validators import DataRequired, URL, Regexp,Length


class NewScanTaskForm(FlaskForm):
    Name = StringField(
        "任务名称",
        validators=[
            Length(4, 32),
            DataRequired(),
            Regexp('^[A-Za-z][A-Za-z0-9_.]*$', 0, '任务名称必须有字母数字或下划线组成')
        ],
        default="Task_Name"
    )
    StartURL = StringField("起始URL", validators=[DataRequired(), URL()], default="http://www.demo.net")
    # ScanPolicy = SelectField("扫描策略", validators=[DataRequired])
    # Select类型，下拉单选框，choices里的内容会在Option里，里面每个项是(值，显示名)对
    ScanPolicy = SelectField('扫描策略', choices=[
        ('Normal', 'Normal'),
        ('Quick', 'Quick'),
        ('Full', 'Full'),
    ], validators=[DataRequired()], default='Normal')
    submit_new = SubmitField('新建任务')
    submit_new_and_start = SubmitField('新建任务并运行')
    #
    # def __init__(self, name="", url="", policy="Normal"):
    #     pass
    #     # NewScanTaskForm.Name.data = name
    #     # NewScanTaskForm.StartURL.data = url
    #     # NewScanTaskForm.ScanPolicy.data = policy

app/monitor/__init__.py
#! /usr/bin/env python
# _*_coding:utf-8 -*_

from flask import Blueprint

monitor = Blueprint("monitor", __name__)

from . import views, errors

app/monitor/views.py
import logging
from flask import render_template, redirect, url_for, request
from flask_socketio import emit

from . import monitor
from .forms import ScanControlForm

from app.lib import MessageBus, CommonMsg
from app.ccserver import CCServerConfig
from app.scan_session import ScanSetting, AgentsState, WvssState, GlobalVar


logger = logging.getLogger("Server")


@monitor.route("/", methods=["GET", "POST"])
def index():
    scan_control_form = ScanControlForm()

    if scan_control_form.is_submitted():
        task_name, start_url, scan_policy = ScanSetting().get_scan_setting()
        if task_name is "" or start_url is "":
            return redirect(url_for("monitor.index"))

        if request.form.get("submit_start_scan") == u"开始扫描":
            start_scan_cmd = {
                    "Type": "WVSCommand",
                    "Data": {
                        "Action": "StartNewScan",
                        "Config": {  # 可选，当命令为StartNewScan时需提供该字段作为扫描参数
                            "StartURL": start_url,
                            "ScanPolicy": scan_policy
                        }
                    }
            }

            CommonMsg.msg_server_command.data = start_scan_cmd
            MessageBus.send_msg(CommonMsg.msg_server_command)

            WvssState().set_current_scan_config(ScanSetting().get_scan_setting())
            GlobalVar.ScanState = "Started"
            logger.info("Start scan....")

            return redirect(url_for("monitor.index"))
        elif request.form.get("submit_stop_scan") == u"停止扫描":
            stop_scan_cmd = {
                "Type": "WVSCommand",
                "Data": {
                    "Action": "StopScan",
                }
            }

            CommonMsg.msg_server_command.data = stop_scan_cmd
            MessageBus.send_msg(CommonMsg.msg_server_command)
            WvssState().set_current_scan_config(None)
            GlobalVar.ScanState = "Stopped"
            logger.info("Stopped scan")
            return redirect(url_for("monitor.index"))
        else:
            pass

    return render_template(
        "monitor.html",
        title="监控中心",
        server_config=CCServerConfig(),
        scan_config=WvssState().get_current_scan_config(),
        agent_state_list=AgentsState().get_agent_list(),
        wvs_state_list=WvssState().get_wvs_state_list(),
        scan_state=GlobalVar.ScanState,
        scan_control_form=scan_control_form
    )


@GlobalVar.SocketIO.on("connect", namespace="/agent_state_ns")
def ws_agent_state_connect():
    # MessageBus.add_msg_listener(CommonMsg.MSG_AGENT_STATE_UPDATE, ws_agent_state_send)
    logger.info("Agent state websocket is connected")


def ws_agent_state_send(msg):
    agent_state = msg.data
    AgentsState().add_agent_state(agent_state)
    GlobalVar.SocketIO.emit(
    # emit(
        "agent_state_update",
        agent_state,
        namespace="/agent_state_ns"
    )
    logger.info("Send agent state: {}".format(agent_state))


@GlobalVar.SocketIO.on("connect", namespace="/wvs_state_ns")
def ws_wvs_state_connect():
    # MessageBus.add_msg_listener(CommonMsg.MSG_WVS_STATE, ws_wvs_state_send)
    logger.info("Wvs state websocket is connected")


def ws_wvs_state_send(msg):
    wvs_state = msg.data
    WvssState().add_wvs_state(wvs_state)
    GlobalVar.SocketIO.emit(
        "wvs_state_update",
        wvs_state,
        namespace="/wvs_state_ns"
    )
    logger.info("Send wvs state: {}".format(wvs_state))

app/result/__init__.py
#! /usr/bin/env python
# _*_coding:utf-8 -*_

from flask import Blueprint

result = Blueprint("result", __name__)

from . import views, errors

app/result/views.py
import time
import logging
import os
from flask import render_template, redirect, url_for, flash, send_file

from . import result
from .gen_report_file import GenReport
from app.scan_session import *

logger = logging.getLogger("Server")


@result.route("/", methods=['GET', 'POST'])
def index():
    return render_template("result.html",
                           title="扫描结果",
                           scan_result_list=ScanResult().wvs_result_list)


@result.route("/report/<timestramp>", methods=['GET', 'POST'])
def report(timestramp):
    gen_report = GenReport()
    gen_report.gen_report()
    return send_file(os.path.join(gen_report.report_path,
                                  gen_report.report_file_name),
                     as_attachment=True)
    # return send_from_directory(gen_report.report_path, gen_report.report_file_name, as_attachment=True)


@result.route("/save", methods=['GET', 'POST'])
def save():
    task_name = WvssState().get_current_scan_config()[0]
    logger.info("保存任务{}".format(task_name))
    # stm.add_new_task(ScanSetting().scan_name)
    ScanTaskManager().save_task(task_name)

    logger.info("任务列表：{}".format(ScanTaskManager().scan_task_list))

    return render_template("result.html",
                           title="扫描结果",
                           scan_result_list=ScanResult().wvs_result_list)


def scan_result_handler(msg):
    scan_res = msg.data
    ScanResult().add_scan_result(scan_res)
    existed = ScanResult().has(scan_res)
    if not existed:
        logger.info("Recive result data:\t{}".format(scan_res))
    GlobalVar.SocketIO.emit("wvs_result_update",
                            scan_res,
                            namespace="/wvs_result")
    logger.info("Send agent state: {}".format(scan_res))


@GlobalVar.SocketIO.on("connect", namespace="/wvs_result")
def wvs_result_connect():
    logger.info("Wvs result websocket is connected")

app/task/__init__.py
#! /usr/bin/env python
# _*_coding:utf-8 -*_

from flask import Blueprint

task = Blueprint("task", __name__)

from . import views, errors

app/task/views.py
import time, logging
from flask import render_template, redirect, url_for,flash, request

from . import task
from .forms import NewScanTaskForm
from app.scan_session import *
from app.lib import MessageBus, CommonMsg

log = logging.getLogger("Server")


@task.route("/", methods=['GET', 'POST'])
def index():
    new_task_form = NewScanTaskForm()
    task_info_list, _ = ScanTaskManager().load_all_task_info()
    task_name = WvssState().get_current_scan_config()[0]

    if new_task_form.is_submitted():
        if not new_task_form.Name.validate(new_task_form) :
            log.info("任务名称错误")
        elif not new_task_form.StartURL.validate(new_task_form):
            log.info("URL名称错误")
        else:
            task_name = new_task_form.Name.data
            start_url = new_task_form.StartURL.data
            scan_policy = new_task_form.ScanPolicy.data
            log.info("{}>>{}>>{}".format(task_name, start_url, scan_policy))

            ScanTaskManager().new_task(task_name, start_url, scan_policy)
            task_info_list, _ = ScanTaskManager().load_all_task_info()

            if request.form.get("submit_new_and_start") == u"新建任务并运行":
                setting = ScanSetting()
                WvssState().set_current_scan_config(ScanSetting().get_scan_setting())
                start_scan_cmd = {
                    "Type": "WVSCommand",
                    "Data": {
                        "Action": "StartNewScan",
                        "Config": {
                            "StartURL": setting.start_url,
                            "ScanPolicy": setting.scan_policy
                        }
                    }
                }
                CommonMsg.msg_server_command.data = start_scan_cmd
                MessageBus.send_msg(CommonMsg.msg_server_command)
                GlobalVar.ScanState = "Started"
                log.info("Start scan....")
                return redirect(url_for("monitor.index"))

            return redirect(url_for('task.index'))

    return render_template('task.html',
                           title="扫描任务管理",
                           NewTaskForm=new_task_form,
                           task_info_list=task_info_list,
                           scan_state=GlobalVar.ScanState,
                           run_task_name=task_name
                           )


@task.route("/delete/<task_name>", methods=['GET', 'POST'])
def delete(task_name):
    if task_name:
        log.info("删除任务: {}".format(task_name))
        log.info("删除前任务: {}".format(ScanTaskManager().scan_task_list))
        ScanTaskManager().del_task(task_name)

        return redirect(url_for("task.index"))


@task.route("/result_info/<task_name>",methods=['GET', 'POST'])
def result_info(task_name):
    if task_name:
        _, scan_config, result_list = ScanTaskManager().load_task_info(task_name)
        WvssState().set_current_scan_config(scan_config)
        log.info(result_list)
        return redirect(url_for("result.index"))


@task.route("/start_scan/<task_name>", methods=['GET', 'POST'])
def start_scan(task_name):
    _, scan_setting, _ = ScanTaskManager().load_task_info(task_name)
    if scan_setting[1] is "":
        return redirect(url_for("task.index"))

    ScanTaskManager().save_task(task_name)

    start_scan_cmd = {
        "Type": "WVSCommand",
        "Data": {
            "Action": "StartNewScan",
            "Config": {  # 可选，当命令为StartNewScan时需提供该字段作为扫描参数
                "StartURL": scan_setting[1],
                "ScanPolicy": scan_setting[2]
            }
        }
    }
    WvssState().set_current_scan_config(ScanSetting().get_scan_setting())

    CommonMsg.msg_server_command.data = start_scan_cmd
    MessageBus.send_msg(CommonMsg.msg_server_command)

    GlobalVar.ScanState = "Started"
    log.info("Start scan....")

    return redirect(url_for("monitor.index"))


@task.route("/stop_scan/<task_name>", methods=['GET', 'POST'])
def stop_scan(task_name):
    stop_scan_cmd = {
        "Type": "WVSCommand",
        "Data": {
            "Action": "StopScan",
        }
    }
    _, scan_setting, _ = ScanTaskManager().load_task_info(task_name)

    CommonMsg.msg_server_command.data = stop_scan_cmd
    MessageBus.send_msg(CommonMsg.msg_server_command)
    WvssState().set_current_scan_config(None)
    GlobalVar.ScanState = "Stopped"
    log.info("Stopped scan")
    return redirect(url_for("task.index"))

app/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="../static/images/favicon_16.ico"/>
    <link rel="bookmark" href="../static/images/favicon_16.ico"/>
    <title>
        {% if title %}
            {{ title }} - WVS 控制中心
        {% else %}
            WVS 控制中心
        {%endif%}
    </title>
    <link rel="stylesheet" type="text/css" href="../static/css/site.css" />
    <link rel="stylesheet" type="text/css" href="../static/css/bootstrap.min.css" />

    <script src="../static/js/jquery-3.3.1.js"></script>
    <script src="../static/js/modernizr-2.6.2.js"></script>

    <script src="https://cdn.bootcss.com/socket.io/1.5.1/socket.io.min.js"></script>
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="{{ url_for('main.index') }}" class="navbar-brand">WVS控制中心</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for("task.index") }}">任务管理</a></li>
                    <li><a href="{{ url_for("monitor.index") }}">监控中心</a></li>
                    <li><a href="{{ url_for("result.index") }}">扫描结果</a></li>
                    <li><a href="#">使用说明</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        {% block content %}{% endblock %}
        <hr />
        <footer>
            <p>&copy; {{ year }} - Web漏洞扫描集中管控系统</p>
        </footer>
    </div>
    <script src="../static/js/jquery-3.3.1.js"></script>
    <script src="../static/js/bootstrap.js"></script>
    {% block scripts %}{% endblock %}
</body>
</html>

app/templates/formhelper.html
{% macro render_field(field) %}
<div class="form-group">
      {{ field.label }}
      {{ field(**kwargs)|safe }}
          {% if field.errors %}
                <ul class=errors>
                {% for error in field.errors %}
                <li>{{ error }}</li>
                {% endfor %}
                </ul>
          {% endif %}
</div>
{% endmacro %}

app/templates/index.html
{% extends "base.html" %}

{% block content %}

<div class="jumbotron">
    <h1>Web漏洞扫描系统集中控制系统</h1>
</div>

<div class="row">
    <div class="col-md-4" style="display: table-cell; vertical-align: middle;">
        <img border="0" src="../static/images/Appscan.jpg" width="240" height="180">
    </div>
    <div class="col-md-4" style="display: table-cell; vertical-align: middle;">
        <img src="../static/images/HP.jpg" width="240" height="180" >
    </div>
    <div class="col-md-4" style="display: table-cell; vertical-align: middle;">
        <img src="../static/images/nsfocus.jpeg" width="240" height="180" >
    </div>
</div>

{% endblock %}

app/templates/report.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{title}}</title>
    <link rel="stylesheet" type="text/css" href="./css/site.css" />
    <link rel="stylesheet" type="text/css" href="./css/bootstrap.css" />
    <script src="./js/jquery-3.3.1.js"></script>
    <script src="./js/modernizr-2.6.2.js"></script>
</head>
<body>
<div class="container body-content" width="80%">
<div class="row">
    <div class="col-lg-12">
        <h1>{{ scan_config[0] }}扫描结果 </h1>
    </div>
    <div class="col-lg-12">
        <!-- col-lg-6 start here -->
        <div class="panel panel-info toggle panelRefresh" id="spr_6">
            <!-- Start .panel -->
            <div class="panel-heading">
                <h4 class="panel-title">扫描参数</h4>
                <div class="panel-controls panel-controls-hide" style="display: none;"><a href="#" class="panel-refresh"><i class="im-spinner6"></i></a><a href="#" class="toggle panel-minimize"><i class="im-minus"></i></a></div></div>
            <div class="panel-body"  style="margin: 0px; padding: 0px;">
                <form action="#" class="form-horizontal" >
                    <div class="form-group" style="margin: 0px; padding: 0px;" >
                        <label class="col-lg-3 control-label" >任务名称</label>
                        <div class="col-lg-9">
                            <label class="control-label">{{scan_config[0]}}</label>
                        </div>
                    </div>
                    <div class="form-group" style="margin: 0px; padding: 0px;" >
                        <label class="col-lg-3 control-label" >扫描起始URL</label>
                        <div class="col-lg-9">
                            <label class="control-label">{{scan_config[1]}}</label>
                        </div>
                    </div>
                    <div class="form-group" style="margin: 0px; padding: 0px;">
                        <label class="col-lg-3 control-label">扫描策略</label>
                        <div class="col-lg-9">
                            <label class="control-label">{{scan_config[2]}}</label>
                        </div>
                    </div>
                    <div class="form-group" style="margin: 0px; padding: 0px;">
                        <label class="col-lg-3 control-label">&nbsp;</label>
                        <div class="col-lg-9">
                            <label class="control-label">&nbsp;</label>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-12 ">
    <div class="panel panel-primary plain toggle panelClose panelRefresh" id="spr_1"  style="margin: 0px; padding: 0px;">
                                <!-- Start .panel -->
        <div class="panel-heading white-bg">
            <h4 class="panel-title">扫描结果</h4>
            <div class="panel-controls panel-controls-hide" style="display: none;">
                <a href="#" class="panel-refresh"><i class="im-spinner6"></i></a>
                <a href="#" class="toggle panel-minimize"><i class="im-minus"></i></a>
                <a href="#" class="panel-close"><i class="im-close"></i></a>
            </div>
        </div>
        <div class="panel-body">
            <div class="slimScrollDiv" style="position: relative; overflow: hidden; width: 100%; height: auto;">
                <div class="table-responsive" style="overflow: hidden; width: 100%; height: auto;">
                    <table class="table table-bordered table-hover" id="wvs_result_table" >
                        <thead>
                            <tr>
                                <th  width="5%">#</th>
                                <th class="per40" width="10%">漏洞类型</th>
                                <th class="per15"  width="10%">漏洞URL</th>
                                <th class="per15"  width="5%">漏洞级别</th>
                                <th class="per15" width="70%">漏洞信息</th>
                            </tr>
                        </thead>
                        <tbody id="wvs_result_table_body">
                        {% for res in scan_result_list %}
                                <tr class="active" id='Result_{{ res["VulType"] }}_{{res["VulUrl"]}}'>
                                    <td>{{loop.index}}</td>
                                    <td>{{res["VulUrl"]}}</td>
                                    <td>{{res["VulType"]}}</td>
                                    <td>{{res["VulSeverity"]}}</td>
                                    <td>
                                    <table class="table table-condensed table-hover" id="vul_detail_{{loop.index}}" style="word-break:break-all; word-wrap:break-spaces;">
                                        <thead>
                                            <tr>
                                                <th class="per40" width="40%">参数变异</th>
                                                <th class="per15" width="40%">漏洞原因</th>
                                                <th class="per15">CWE</th>
                                                <th class="per15">CVE</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        {% for vul_detail in res["VulDetails"] %}
                                            <tr class="info">
                                                <td>{{vul_detail["url_param_variant"]}}</td>
                                                <td>{{vul_detail["vul_reasoning"]}}</td>
                                                <td>{{vul_detail["CWE"]}}</td>
                                                <td>{{vul_detail["CVE"]}}</td>
                                            </tr>
                                         {% endfor %}
                                        </tbody>
                                    </table>
                                        </td>

                                </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
</div>
</body>
</html>

app/templates/task.html
{% extends "base.html" %}

{% block content %}

<script>
   function getCookie(cname){
        var name = cname + "=";
        var ca = document.cookie.split(';');
        for(var i=0; i<ca.length; i++){
            var c = ca[i].trim();
            if (c.indexOf(name)==0)
                return c.substring(name.length,c.length);
        }
        return "";
    }
    function setCookie(cname,cvalue,exdays)
    {
      var d = new Date();
      d.setTime(d.getTime()+(exdays*24*60*60*1000));
      var expires = "expires="+d.toGMTString();
      document.cookie = cname + "=" + cvalue + "; " + expires;
    }
    function restart_scan(name) {
        var server_state = getCookie("ServerState")
        if (server_state == "Started") {
            setCookie("ScanState", "Started", 1)
            var url = window.location.href
            console.log(url)
            url = url + "/restart/" + name
            window.location = url
        }
        else {
            alert("服务器未启动")
        }
    }
</script>
<h2>{{ title }}</h2>
<h3>{{ message }}</h3>
<div class="content-row">
    <div class="panel panel-default">
        <div class="panel-heading">
            <div class="panel-title">

            </div>
            <div class="panel-options">
                <a class="bg" data-target="#sample-modal-dialog-1" data-toggle="modal" href="#sample-modal"><i class="entypo-cog"></i></a>
                <a data-rel="collapse" href="#"><i class="entypo-down-open"></i></a>
                <a data-rel="close" href="#!/tasks" ui-sref="Tasks"><i class="entypo-cancel"></i></a>
            </div>
        </div>
        <div class="panel-body">

              <form role="form" action="/task/", method="POST">
                  {% from "formhelper.html" import render_field %}
                      <div class="form-group">
                          {{ render_field(NewTaskForm.Name,class="form-control",id="Name",placeholder="Task_Name") }}
                      </div>
                      <div class="form-group">
                          {{ render_field(NewTaskForm.StartURL,class="form-control",id="Name",placeholder="Task_Name") }}
                      </div>
                      <div class="form-group">
                            {{ render_field(NewTaskForm.ScanPolicy,class="form-control",id="Name",placeholder="Task_Name") }}
                      </div>
                      {{ NewTaskForm.submit_new(class="btn btn-default") }}&nbsp;&nbsp;&nbsp;{{ NewTaskForm.submit_new_and_start(class="btn btn-default") }}
              </form>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-12 ">
    <div class="panel panel-primary plain toggle panelClose panelRefresh" id="spr_1"  style="margin: 0px; padding: 0px;">
                                <!-- Start .panel -->
        <div class="panel-heading white-bg">
            <h4 class="panel-title">任务列表</h4>
            <div class="panel-controls panel-controls-hide" style="display: none;">
                <a href="#" class="panel-refresh"><i class="im-spinner6"></i></a>
                <a href="#" class="toggle panel-minimize"><i class="im-minus"></i></a>
                <a href="#" class="panel-close"><i class="im-close"></i></a>
            </div>
        </div>
        <div class="panel-body">
            <div class="slimScrollDiv" style="position: relative; overflow: hidden; width: 100%; height: auto;">
                <div class="table-responsive" style="overflow: hidden; width: 100%; height: auto;">
                    <table class="table table-bordered table-hover" id="wvs_result_table" >
                        <thead>
                            <tr>
                                <th  width="5%">#</th>
                                <th class="per40" width="10%">任务名称</th>
                                <th class="per15"  width="20%">目标URL</th>
                                <th class="per15"  width="10%">扫描策略</th>
                                <th class="per15" width="15%">任务时间</th>
                                <th class="per15" width="20%">结果信息</th>
                                <th class="per15" >操作</th>
                            </tr>
                        </thead>
                        <tbody id="wvs_result_table_body">
                            {% if task_info_list  %}
                                {% for task_info in task_info_list %}
                                <tr class="active" id='Task_{{ task_info["TaskName"] }}'>
                                    <td>{{loop.index}}</td>
                                    <td>{{ task_info["TaskName"] }}</td>
                                    <td>{{ task_info["ScanSetting"]["StartURL"] }}</td>
                                    <td>{{ task_info["ScanSetting"]["ScanPolicy"]}}</td>
                                    <td>{{ task_info["Timestamp"] }}</td>
                                    <td><a href="{{url_for('task.result_info', task_name=task_info['TaskName'])}}">结果信息</a></td>
                                    <td>
                                    {% if scan_state == "Stopped" %}
                                             <a href="{{url_for('task.delete', task_name=task_info['TaskName'])}}" >删除</a>&nbsp;
                                             <a href="{{url_for('task.start_scan', task_name=task_info['TaskName'])}}">开始扫描</a>&nbsp;
                                            <span>停止扫描</span>
                                    {% elif scan_state ==  "Started" %}
                                        {% if run_task_name != task_info["TaskName"] %}
                                            <span>删除</span>&nbsp;
                                            <span>开始扫描</span>&nbsp;
                                            <span>停止扫描</span>
                                        {% elif run_task_name == task_info["TaskName"] %}
                                            <span>删除</span>&nbsp;
                                             <span >开始扫描</span>&nbsp;
                                             <a href="{{url_for('task.stop_scan', task_name=task_info['TaskName'])}}">停止扫描</a>
                                        {% endif %}
                                    {% endif %}
                                    </td>
                                {% endfor %}
                            {% endif %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
</div>

{% endblock %}